services:
  audiotrans:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "${PORT:-8001}:8001"
    environment:
      - API_KEY=${API_KEY:-audio-trans-secret-key-2024}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WHISPER_MODEL=${WHISPER_MODEL:-tiny}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-100MB}
      - PORT=8001
      - PYTHONUNBUFFERED=1
    volumes:
      - temp_data:/tmp/audiotrans
    # Temporalmente desactivado para debugging
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
    #   interval: 60s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 120s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 1.5G

volumes:
  temp_data: 