version: '3.8'

services:
  audiotrans:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      # Valores por defecto que pueden ser sobrescritos por .env
      - API_KEY=${API_KEY:-audio-trans-secret-key-2024}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WHISPER_MODEL=${WHISPER_MODEL:-small}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-100MB}
    volumes:
      # Volumen para archivos temporales (opcional)
      - ./temp:/tmp/audiotrans
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 60s
    restart: unless-stopped 